language: node_js
node_js: [ "8" ]

before_script:
- travis_wait npm run setup
- echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc

script:
- npm run test
- npm run build
- npm whoami
- |
  if [ -n "$TRAVIS_TAG" ]; then 
    npm run publish; 
  else 
    echo 'Not a tag, skipping publish';
  fi

