language: node_js
node_js: [ "8" ]

before_script:
- travis_wait npm run setup

script:
- npm run test
- npm run build
- |
  if [ -n "$TRAVIS_TAG" ]; then 
    npm run publish; 
  else 
    echo 'Not a tag, skipping publish';
  fi

