language: node_js
node_js: [ "8" ]

before_script:
- travis_wait npm run setup

script:
- npm run build
- npm run test
- '[ -n $TRAVIS_TAG ] && npm publish'

deploy:
  provider: script
  script: npm run publish
  skip_cleanup: true
  on:
    branch: master
    tags: true

